sudo: required

language: node_js

cache: yarn

branches:
  only:
  - gh-pages
  - /.*/

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest
  chrome: stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn start
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8080 &

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - yarn flow
  - yarn lint
  - yarn test
  - yarn test:e2e:all