sudo: required

language: node_js

cache: yarn

branches:
  only:
  - gh-pages
  - /.*/

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest
  chrome: stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - yarn start &
  - sleep 3

jobs:
  include:
    - stage: tests
      script: yarn flow
    - stage: tests
      script: yarn lint
    - stage: tests
      script: yarn test
    - stage: tests
      script: yarn test:e2e:all
